<a href="https://colab.research.google.com/github/Nikhilth123/Learning-basics-of-llms/blob/main/pandas_df.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#creating dataframe
student_data=[
    [130,45,15],
    [34,12,12],
    [23,23,45],
    [56,67,89]
]
pd.DataFrame(student_data,columns=['iq','marks','package'])

    iq  marks  package
0  130     45       15
1   34     12       12
2   23     23       45
3   56     67       89

In [ ]:
students_dict={
    'iq':[130,34,23,56],
    'marks':[45,12,23,67],
    'package':[15,12,45,89]

};
students=pd.DataFrame(students_dict)
students

    iq  marks  package
0  130     45       15
1   34     12       12
2   23     23       45
3   56     67       89

In [ ]:
movies=pd.read_csv('/content/BollywoodMovieDetail.csv')
movies

,imdbId,title,releaseYear,releaseDate,genre,writers,actors,directors,sequel,hitFlop
0,tt0118578,Albela,2001,20 Apr 2001,Romance,Honey Irani (screenplay) | Honey Irani (story)...,Govinda | Aishwarya Rai Bachchan | Jackie Shro...,Deepak Sareen,0.0,2
1,tt0169102,Lagaan: Once Upon a Time in India,2001,08 May 2002,Adventure | Drama | Musical,Ashutosh Gowariker (story) | Ashutosh Gowarike...,Aamir Khan | Gracy Singh | Rachel Shelley | Pa...,Ashutosh Gowariker,0.0,6
2,tt0187279,Meri Biwi Ka Jawab Nahin,2004,02 Jul 2004,Action | Comedy,NaN,Akshay Kumar | Sridevi | Gulshan Grover | Laxm...,Pankaj Parashar | S.M. Iqbal,0.0,1
3,tt0222024,Hum Tumhare Hain Sanam,2002,24 May 2002,Drama | Romance,K.S. Adiyaman | Arun Kumar (assistant dialogue...,Shah Rukh Khan | Madhuri Dixit | Salman Khan |...,K.S. Adiyaman,0.0,4
4,tt0227194,One 2 Ka 4,2001,30 Mar 2001,Action | Comedy | Drama,Sanjay Chhel | Raaj Kumar Dahima (screenplay) ...,Shah Rukh Khan | Juhi Chawla | Jackie Shroff |...,Shashilal K. Nair,0.0,1
...,...,...,...,...,...,...,...,...,...,...
1279,tt4121522,Shuruaat Ka Interval,2014,15 Aug 2014,NaN,Aarti S. Bagdi | Amrit Raj Gupta | Krishan Hoo...,Kaivalya Chheda | Rajsekhar Aningi | Avidant B...,Aarti S. Bagdi | Amrit Raj Gupta | Krishan Hoo...,0.0,1
1280,tt4187650,Trip to Bhangarh,2014,28 Aug 2014,Horror,NaN,Manish Choudhary | Suzanna Mukherjee | Poonam ...,Jitendra Pawar,0.0,1
1281,tt4190220,Zed Plus,2014,28 Nov 2014,NaN,Chandra Prakash Dwivedi (screen play and dialo...,Adil Hussain | Ekavali Khanna | Kulbhushan Kha...,Chandra Prakash Dwivedi,0.0,1
1282,tt4219300,Gollu aur Pappu,2014,21 Nov 2014,Comedy,NaN,Vir Das | Sandeepa Dhar | Rahul Handa | Dimple...,Kabir Sadanand,0.0,1
1283,tt4228746,Zid,2014,28 Nov 2014,Thriller,Vivek Agnihotri | Rohit Malhotra,Shradha Das | Mohan Kapoor | Mannara | Karanvi...,Rohit Malhotra | Anubhav Sinha,0.0,2

In [ ]:
player=pd.read_csv('/content/2024_players_details.csv')
player

,ID,Name,longName,battingName,fieldingName,imgUrl,dob,battingStyles,longBattingStyles,bowlingStyles,longBowlingStyles,playingRoles,espn_url
0,95094,RD Gaikwad,Ruturaj Gaikwad,RD Gaikwad,Gaikwad,"https://img1.hscicdn.com/image/upload/f_auto,t...",31/1/1997,rhb,right-hand bat,ob,right-arm offbreak,ob,https://www.espncricinfo.com/cricketers/rutura...
1,46597,MM Ali,Moeen Ali,MM Ali,Ali,"https://img1.hscicdn.com/image/upload/f_auto,t...",18/6/1987,lhb,left-hand bat,ob,right-arm offbreak,ob,https://www.espncricinfo.com/cricketers/moeen-...
2,116328,Aravelly Avanish,Aravelly Avanish,Aravelly Avanish,Aravelly Avanish,"https://img1.hscicdn.com/image/upload/f_auto,t...",2/6/2005,lhb,left-hand bat,Na,Na,NaN,https://www.espncricinfo.com/cricketers/aravel...
3,62022,DL Chahar,Deepak Chahar,DL Chahar,Chahar,"https://img1.hscicdn.com/image/upload/f_auto,t...",7/8/1992,rhb,right-hand bat,rm,right-arm medium,rm,https://www.espncricinfo.com/cricketers/deepak...
4,80607,TU Deshpande,Tushar Deshpande,TU Deshpande,Deshpande,"https://img1.hscicdn.com/image/upload/f_auto,t...",15/5/1995,lhb,left-hand bat,rm,right-arm medium,rm,https://www.espncricinfo.com/cricketers/tushar...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,59261,JD Unadkat,Jaydev Unadkat,JD Unadkat,Unadkat,"https://img1.hscicdn.com/image/upload/f_auto,t...",18/10/1991,rhb,right-hand bat,lm,left-arm medium,lm,https://www.espncricinfo.com/cricketers/jaydev...
257,102870,V Viyaskanth,Vijayakanth Viyaskanth,V Viyaskanth,Viyaskanth,"https://img1.hscicdn.com/image/upload/f_auto,t...",5/12/2001,rhb,right-hand bat,lb,legbreak,lb,https://www.espncricinfo.com/cricketers/vijaya...
258,75311,Washington Sundar,Washington Sundar,Washington Sundar,Washington Sundar,"https://img1.hscicdn.com/image/upload/f_auto,t...",5/10/1999,lhb,left-hand bat,ob,right-arm offbreak,ob,https://www.espncricinfo.com/cricketers/washin...
259,75985,UD Yadav,Upendra Yadav,UD Yadav,Yadav,"https://img1.hscicdn.com/image/upload/f_auto,t...",8/10/1996,rhb,right-hand bat,ob,right-arm offbreak,ob,https://www.espncricinfo.com/cricketers/upendr...
260,78239,PW Hasaranga,Wanindu Hasaranga,PW Hasaranga,Hasaranga,"https://img1.hscicdn.com/image/upload/f_auto,t...",29/7/1997,rhb,right-hand bat,lb,legbreak,lb,https://www.espncricinfo.com/cricketers/wanind...

In [ ]:
movies.shape

(1284, 10)

In [ ]:
player.shape

(261, 13)

In [ ]:
movies.dtypes

imdbId          object
title           object
releaseYear      int64
releaseDate     object
genre           object
writers         object
actors          object
directors       object
sequel         float64
hitFlop          int64
dtype: object

In [ ]:
movies.index

RangeIndex(start=0, stop=1284, step=1)

In [ ]:
movies.columns

Index(['imdbId', 'title', 'releaseYear', 'releaseDate', 'genre', 'writers',
       'actors', 'directors', 'sequel', 'hitFlop'],
      dtype='object')

In [ ]:
students.values

array([[130,  45,  15],
       [ 34,  12,  12],
       [ 23,  23,  45],
       [ 56,  67,  89]])

In [ ]:
movies.head()

,imdbId,title,releaseYear,releaseDate,genre,writers,actors,directors,sequel,hitFlop
0,tt0118578,Albela,2001,20 Apr 2001,Romance,Honey Irani (screenplay) | Honey Irani (story)...,Govinda | Aishwarya Rai Bachchan | Jackie Shro...,Deepak Sareen,0.0,2
1,tt0169102,Lagaan: Once Upon a Time in India,2001,08 May 2002,Adventure | Drama | Musical,Ashutosh Gowariker (story) | Ashutosh Gowarike...,Aamir Khan | Gracy Singh | Rachel Shelley | Pa...,Ashutosh Gowariker,0.0,6
2,tt0187279,Meri Biwi Ka Jawab Nahin,2004,02 Jul 2004,Action | Comedy,NaN,Akshay Kumar | Sridevi | Gulshan Grover | Laxm...,Pankaj Parashar | S.M. Iqbal,0.0,1
3,tt0222024,Hum Tumhare Hain Sanam,2002,24 May 2002,Drama | Romance,K.S. Adiyaman | Arun Kumar (assistant dialogue...,Shah Rukh Khan | Madhuri Dixit | Salman Khan |...,K.S. Adiyaman,0.0,4
4,tt0227194,One 2 Ka 4,2001,30 Mar 2001,Action | Comedy | Drama,Sanjay Chhel | Raaj Kumar Dahima (screenplay) ...,Shah Rukh Khan | Juhi Chawla | Jackie Shroff |...,Shashilal K. Nair,0.0,1

In [ ]:
movies.tail()

,imdbId,title,releaseYear,releaseDate,genre,writers,actors,directors,sequel,hitFlop
1279,tt4121522,Shuruaat Ka Interval,2014,15 Aug 2014,NaN,Aarti S. Bagdi | Amrit Raj Gupta | Krishan Hoo...,Kaivalya Chheda | Rajsekhar Aningi | Avidant B...,Aarti S. Bagdi | Amrit Raj Gupta | Krishan Hoo...,0.0,1
1280,tt4187650,Trip to Bhangarh,2014,28 Aug 2014,Horror,NaN,Manish Choudhary | Suzanna Mukherjee | Poonam ...,Jitendra Pawar,0.0,1
1281,tt4190220,Zed Plus,2014,28 Nov 2014,NaN,Chandra Prakash Dwivedi (screen play and dialo...,Adil Hussain | Ekavali Khanna | Kulbhushan Kha...,Chandra Prakash Dwivedi,0.0,1
1282,tt4219300,Gollu aur Pappu,2014,21 Nov 2014,Comedy,NaN,Vir Das | Sandeepa Dhar | Rahul Handa | Dimple...,Kabir Sadanand,0.0,1
1283,tt4228746,Zid,2014,28 Nov 2014,Thriller,Vivek Agnihotri | Rohit Malhotra,Shradha Das | Mohan Kapoor | Mannara | Karanvi...,Rohit Malhotra | Anubhav Sinha,0.0,2

In [ ]:
movies.sample(5)

,imdbId,title,releaseYear,releaseDate,genre,writers,actors,directors,sequel,hitFlop
641,tt1214948,Bhram: An Illusion,2008,04 Apr 2008,Drama | Mystery | Romance,Bhavani Iyer (screenplay) | Radhika Anand (dia...,Dino Morea | Milind Soman | Sheetal Menon | Si...,Pavan Kaul,0.0,1
646,tt1218345,Dil Kabaddi,2008,05 Dec 2008,Comedy | Drama,Vivek Anand | Anil Senior | Lezlie George Sparkx,Irrfan Khan | Rahul Bose | Rahul Khanna | Konk...,Anil Senior,0.0,2
115,tt0335044,Dil Vil Pyar Vyar,2002,18 Oct 2002,Romance,Sanjeev Puri (dialogue) | Sujit Sen (screenpla...,Madhavan | Jimmy Shergill | Sanjay Suri | Namr...,Anant Mahadevan,0.0,2
635,tt1199490,Bad Luck Govind,2009,09 Jan 2009,Comedy | Crime | Drama,Varun Khanna (dialogue),Gaurav Kapoor | Hrishitaa Bhatt | Govind Namde...,Varun Khanna,0.0,1
1264,tt3709344,CityLights,2014,30 May 2014,Drama | Thriller,Sean Ellis (original story) | Ritesh Shah (ada...,Rajkummar Rao | Mallhar Goenka | Manav Kaul | ...,Hansal Mehta,0.0,2

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1284 entries, 0 to 1283
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   imdbId       1284 non-null   object
 1   title        1284 non-null   object
 2   releaseYear  1284 non-null   int64
 3   releaseDate  1231 non-null   object
 4   genre        1282 non-null   object
 5   writers      1165 non-null   object
 6   actors       1281 non-null   object
 7   directors    1280 non-null   object
 8   sequel       1281 non-null   float64
 9   hitFlop      1284 non-null   int64
dtypes: float64(1), int64(2), object(7)
memory usage: 100.4+ KB

In [ ]:
player.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261 entries, 0 to 260
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 261 non-null    int64
 1   Name               261 non-null    object
 2   longName           261 non-null    object
 3   battingName        261 non-null    object
 4   fieldingName       261 non-null    object
 5   imgUrl             261 non-null    object
 6   dob                261 non-null    object
 7   battingStyles      261 non-null    object
 8   longBattingStyles  261 non-null    object
 9   bowlingStyles      261 non-null    object
 10  longBowlingStyles  261 non-null    object
 11  playingRoles       237 non-null    object
 12  espn_url           261 non-null    object
dtypes: int64(1), object(12)
memory usage: 26.6+ KB

In [ ]:
player.describe()

                  ID
count     261.000000
mean    80535.095785
std     23353.816863
min      7593.000000
25%     62022.000000
50%     80607.000000
75%    102735.000000
max    116573.000000

In [ ]:
movies.describe()

       releaseYear       sequel      hitFlop
count  1284.000000  1281.000000  1284.000000
mean   2007.989097     0.035129     2.144081
std       4.005243     0.188371     1.812820
min    2001.000000     0.000000     1.000000
25%    2004.000000     0.000000     1.000000
50%    2008.000000     0.000000     1.000000
75%    2011.000000     0.000000     2.000000
max    2014.000000     2.000000     9.000000

In [ ]:
movies.isnull().sum()

imdbId           0
title            0
releaseYear      0
releaseDate     53
genre            2
writers        119
actors           3
directors        4
sequel           3
hitFlop          0
dtype: int64

In [ ]:
movies.duplicated().sum()

np.int64(0)

In [ ]:
students.rename(columns={'marks':'percentage','package':'lpa'},inplace=True)

In [ ]:
students.sum(axis=1)

0    190
1     58
2     91
3    212
dtype: int64

In [ ]:
movies['title']

0                                  Albela
1       Lagaan: Once Upon a Time in India
2                Meri Biwi Ka Jawab Nahin
3                  Hum Tumhare Hain Sanam
4                              One 2 Ka 4
                      ...
1279                 Shuruaat Ka Interval
1280                     Trip to Bhangarh
1281                             Zed Plus
1282                      Gollu aur Pappu
1283                                  Zid
Name: title, Length: 1284, dtype: object

In [ ]:
player['longBattingStyles']

0      right-hand bat
1       left-hand bat
2       left-hand bat
3      right-hand bat
4       left-hand bat
            ...
256    right-hand bat
257    right-hand bat
258     left-hand bat
259    right-hand bat
260    right-hand bat
Name: longBattingStyles, Length: 261, dtype: object

In [ ]:
player.columns

Index(['ID', 'Name', 'longName', 'battingName', 'fieldingName', 'imgUrl',
       'dob', 'battingStyles', 'longBattingStyles', 'bowlingStyles',
       'longBowlingStyles', 'playingRoles', 'espn_url'],
      dtype='object')

In [ ]:
player[['Name','battingStyles','playingRoles']]

                  Name battingStyles playingRoles
0           RD Gaikwad           rhb           ob
1               MM Ali           lhb           ob
2     Aravelly Avanish           lhb          NaN
3            DL Chahar           rhb           rm
4         TU Deshpande           lhb           rm
..                 ...           ...          ...
256         JD Unadkat           rhb           lm
257       V Viyaskanth           rhb           lb
258  Washington Sundar           lhb           ob
259           UD Yadav           rhb           ob
260       PW Hasaranga           rhb           lb

[261 rows x 3 columns]

In [ ]:
player.iloc[0]

ID                                                               95094
Name                                                        RD Gaikwad
longName                                               Ruturaj Gaikwad
battingName                                                 RD Gaikwad
fieldingName                                                   Gaikwad
imgUrl               https://img1.hscicdn.com/image/upload/f_auto,t...
dob                                                          31/1/1997
battingStyles                                                      rhb
longBattingStyles                                       right-hand bat
bowlingStyles                                                       ob
longBowlingStyles                                   right-arm offbreak
playingRoles                                                        ob
espn_url             https://www.espncricinfo.com/cricketers/rutura...
Name: 0, dtype: object

In [ ]:
player.iloc[1]

ID                                                               46597
Name                                                            MM Ali
longName                                                     Moeen Ali
battingName                                                     MM Ali
fieldingName                                                       Ali
imgUrl               https://img1.hscicdn.com/image/upload/f_auto,t...
dob                                                          18/6/1987
battingStyles                                                      lhb
longBattingStyles                                        left-hand bat
bowlingStyles                                                       ob
longBowlingStyles                                   right-arm offbreak
playingRoles                                                        ob
espn_url             https://www.espncricinfo.com/cricketers/moeen-...
Name: 1, dtype: object

In [ ]:
player.iloc[0:16:2]

,ID,Name,longName,battingName,fieldingName,imgUrl,dob,battingStyles,longBattingStyles,bowlingStyles,longBowlingStyles,playingRoles,espn_url
0,95094,RD Gaikwad,Ruturaj Gaikwad,RD Gaikwad,Gaikwad,"https://img1.hscicdn.com/image/upload/f_auto,t...",31/1/1997,rhb,right-hand bat,ob,right-arm offbreak,ob,https://www.espncricinfo.com/cricketers/rutura...
2,116328,Aravelly Avanish,Aravelly Avanish,Aravelly Avanish,Aravelly Avanish,"https://img1.hscicdn.com/image/upload/f_auto,t...",2/6/2005,lhb,left-hand bat,Na,Na,NaN,https://www.espncricinfo.com/cricketers/aravel...
4,80607,TU Deshpande,Tushar Deshpande,TU Deshpande,Deshpande,"https://img1.hscicdn.com/image/upload/f_auto,t...",15/5/1995,lhb,left-hand bat,rm,right-arm medium,rm,https://www.espncricinfo.com/cricketers/tushar...
6,74975,S Dube,Shivam Dube,S Dube,Dube,"https://img1.hscicdn.com/image/upload/f_auto,t...",26/6/1993,lhb,left-hand bat,rm,right-arm medium,rm,https://www.espncricinfo.com/cricketers/shivam...
8,104758,RS Hangargekar,Rajvardhan Hangargekar,RS Hangargekar,Hangargekar,"https://img1.hscicdn.com/image/upload/f_auto,t...",10/11/2002,rhb,right-hand bat,rfm,right-arm fast-medium,rfm,https://www.espncricinfo.com/cricketers/rajvar...
10,95065,AJ Mandal,Ajay Mandal,AJ Mandal,Mandal,"https://img1.hscicdn.com/image/upload/f_auto,t...",25/2/1996,lhb,left-hand bat,sla,slow left-arm orthodox,sla,https://www.espncricinfo.com/cricketers/ajay-m...
12,101414,Mukesh Choudhary,Mukesh Choudhary,Mukesh Choudhary,Mukesh Choudhary,"https://img1.hscicdn.com/image/upload/f_auto,t...",6/7/1996,lhb,left-hand bat,lm,left-arm medium,lm,https://www.espncricinfo.com/cricketers/mukesh...
14,105938,M Pathirana,Matheesha Pathirana,M Pathirana,Pathirana,"https://img1.hscicdn.com/image/upload/f_auto,t...",18/12/2002,rhb,right-hand bat,rf,right-arm fast,rf,https://www.espncricinfo.com/cricketers/mathee...

In [ ]:
player.iloc[[0,6,19]]

,ID,Name,longName,battingName,fieldingName,imgUrl,dob,battingStyles,longBattingStyles,bowlingStyles,longBowlingStyles,playingRoles,espn_url
0,95094,RD Gaikwad,Ruturaj Gaikwad,RD Gaikwad,Gaikwad,"https://img1.hscicdn.com/image/upload/f_auto,t...",31/1/1997,rhb,right-hand bat,ob,right-arm offbreak,ob,https://www.espncricinfo.com/cricketers/rutura...
6,74975,S Dube,Shivam Dube,S Dube,Dube,"https://img1.hscicdn.com/image/upload/f_auto,t...",26/6/1993,lhb,left-hand bat,rm,right-arm medium,rm,https://www.espncricinfo.com/cricketers/shivam...
19,64864,MJ Santner,Mitchell Santner,MJ Santner,Santner,"https://img1.hscicdn.com/image/upload/f_auto,t...",5/2/1992,lhb,left-hand bat,sla,slow left-arm orthodox,sla,https://www.espncricinfo.com/cricketers/mitche...

In [ ]:
player[player['Name'] == 'RD Gaikwad']

,ID,Name,longName,battingName,fieldingName,imgUrl,dob,battingStyles,longBattingStyles,bowlingStyles,longBowlingStyles,playingRoles,espn_url
0,95094,RD Gaikwad,Ruturaj Gaikwad,RD Gaikwad,Gaikwad,"https://img1.hscicdn.com/image/upload/f_auto,t...",31/1/1997,rhb,right-hand bat,ob,right-arm offbreak,ob,https://www.espncricinfo.com/cricketers/rutura...

In [ ]:
start_index = player[player['Name'] == 'RD Gaikwad'].index[0]
end_index = player[player['Name'] == 'Mukesh Choudhary'].index[0]
player.iloc[start_index : end_index + 1]

,ID,Name,longName,battingName,fieldingName,imgUrl,dob,battingStyles,longBattingStyles,bowlingStyles,longBowlingStyles,playingRoles,espn_url
0,95094,RD Gaikwad,Ruturaj Gaikwad,RD Gaikwad,Gaikwad,"https://img1.hscicdn.com/image/upload/f_auto,t...",31/1/1997,rhb,right-hand bat,ob,right-arm offbreak,ob,https://www.espncricinfo.com/cricketers/rutura...
1,46597,MM Ali,Moeen Ali,MM Ali,Ali,"https://img1.hscicdn.com/image/upload/f_auto,t...",18/6/1987,lhb,left-hand bat,ob,right-arm offbreak,ob,https://www.espncricinfo.com/cricketers/moeen-...
2,116328,Aravelly Avanish,Aravelly Avanish,Aravelly Avanish,Aravelly Avanish,"https://img1.hscicdn.com/image/upload/f_auto,t...",2/6/2005,lhb,left-hand bat,Na,Na,NaN,https://www.espncricinfo.com/cricketers/aravel...
3,62022,DL Chahar,Deepak Chahar,DL Chahar,Chahar,"https://img1.hscicdn.com/image/upload/f_auto,t...",7/8/1992,rhb,right-hand bat,rm,right-arm medium,rm,https://www.espncricinfo.com/cricketers/deepak...
4,80607,TU Deshpande,Tushar Deshpande,TU Deshpande,Deshpande,"https://img1.hscicdn.com/image/upload/f_auto,t...",15/5/1995,lhb,left-hand bat,rm,right-arm medium,rm,https://www.espncricinfo.com/cricketers/tushar...
5,7593,MS Dhoni,MS Dhoni,MS Dhoni,Dhoni,"https://img1.hscicdn.com/image/upload/f_auto,t...",7/7/1981,rhb,right-hand bat,rm,right-arm medium,rm,https://www.espncricinfo.com/cricketers/ms-dho...
6,74975,S Dube,Shivam Dube,S Dube,Dube,"https://img1.hscicdn.com/image/upload/f_auto,t...",26/6/1993,lhb,left-hand bat,rm,right-arm medium,rm,https://www.espncricinfo.com/cricketers/shivam...
7,63314,RJ Gleeson,Richard Gleeson,RJ Gleeson,Gleeson,"https://img1.hscicdn.com/image/upload/f_auto,t...",2/12/1987,rhb,right-hand bat,rfm,right-arm fast-medium,rfm,https://www.espncricinfo.com/cricketers/richar...
8,104758,RS Hangargekar,Rajvardhan Hangargekar,RS Hangargekar,Hangargekar,"https://img1.hscicdn.com/image/upload/f_auto,t...",10/11/2002,rhb,right-hand bat,rfm,right-arm fast-medium,rfm,https://www.espncricinfo.com/cricketers/rajvar...
9,49247,RA Jadeja,Ravindra Jadeja,RA Jadeja,Jadeja,"https://img1.hscicdn.com/image/upload/f_auto,t...",6/12/1988,lhb,left-hand bat,sla,slow left-arm orthodox,sla,https://www.espncricinfo.com/cricketers/ravind...
10,95065,AJ Mandal,Ajay Mandal,AJ Mandal,Mandal,"https://img1.hscicdn.com/image/upload/f_auto,t...",25/2/1996,lhb,left-hand bat,sla,slow left-arm orthodox,sla,https://www.espncricinfo.com/cricketers/ajay-m...
11,58772,DJ Mitchell,Daryl Mitchell,DJ Mitchell,Mitchell,"https://img1.hscicdn.com/image/upload/f_auto,t...",20/5/1991,rhb,right-hand bat,rm,right-arm medium,rm,https://www.espncricinfo.com/cricketers/daryl-...
12,101414,Mukesh Choudhary,Mukesh Choudhary,Mukesh Choudhary,Mukesh Choudhary,"https://img1.hscicdn.com/image/upload/f_auto,t...",6/7/1996,lhb,left-hand bat,lm,left-arm medium,lm,https://www.espncricinfo.com/cricketers/mukesh...

In [ ]:
player.iloc[0:6,0:6]

,ID,Name,longName,battingName,fieldingName,imgUrl
0,95094,RD Gaikwad,Ruturaj Gaikwad,RD Gaikwad,Gaikwad,"https://img1.hscicdn.com/image/upload/f_auto,t..."
1,46597,MM Ali,Moeen Ali,MM Ali,Ali,"https://img1.hscicdn.com/image/upload/f_auto,t..."
2,116328,Aravelly Avanish,Aravelly Avanish,Aravelly Avanish,Aravelly Avanish,"https://img1.hscicdn.com/image/upload/f_auto,t..."
3,62022,DL Chahar,Deepak Chahar,DL Chahar,Chahar,"https://img1.hscicdn.com/image/upload/f_auto,t..."
4,80607,TU Deshpande,Tushar Deshpande,TU Deshpande,Deshpande,"https://img1.hscicdn.com/image/upload/f_auto,t..."
5,7593,MS Dhoni,MS Dhoni,MS Dhoni,Dhoni,"https://img1.hscicdn.com/image/upload/f_auto,t..."