<a href="https://colab.research.google.com/github/Nikhilth123/Learning-basics-of-llms/blob/main/pandas_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np

In [5]:
country=['india','nepal','japan','pakistan','bhutan']
pd.Series(country)

0       india
1       nepal
2       japan
3    pakistan
4      bhutan
dtype: object

In [6]:
runs=[5,6,78,99,100,120];
run_ser=pd.Series(runs)

In [7]:
marks=[67,99,98,97,96,100]
subjects=['hindi','maths','english','geo','polity','history']
pd.Series(marks,index=subjects)

hindi       67
maths       99
english     98
geo         97
polity      96
history    100
dtype: int64

In [8]:
pd.Series(marks,index=subjects,name='Nikhil ')

hindi       67
maths       99
english     98
geo         97
polity      96
history    100
Name: Nikhil , dtype: int64

In [9]:
marks={
    'hindi':90,
    'english':88,
    'maths':98,
    'geo':97,
    'polity':96,
    'history':100
}
pd.Series(marks,name='nikhil')

hindi       90
english     88
maths       98
geo         97
polity      96
history    100
Name: nikhil, dtype: int64

In [10]:
marks=pd.Series(marks,index=subjects,name='Nikhil')
marks

hindi       90
maths       98
english     88
geo         97
polity      96
history    100
Name: Nikhil, dtype: int64

In [11]:
#size
marks.size

6

In [12]:
#name
marks.name

'Nikhil'

In [13]:
#dtype
marks.dtype

dtype('int64')

In [14]:
#unique
marks.is_unique

True

In [15]:
pd.Series([1,2,2,4,5,9,9]).is_unique

False

In [16]:
#index
marks.index

Index(['hindi', 'maths', 'english', 'geo', 'polity', 'history'], dtype='object')

In [17]:
run_ser.index

RangeIndex(start=0, stop=6, step=1)

In [18]:
#values
run_ser.values

array([  5,   6,  78,  99, 100, 120])

In [19]:
type(marks.values)

numpy.ndarray

In [20]:
bolly=pd.read_csv('/content/BollywoodMovieDetail.csv')
bolly

,imdbId,title,releaseYear,releaseDate,genre,writers,actors,directors,sequel,hitFlop
0,tt0118578,Albela,2001,20 Apr 2001,Romance,Honey Irani (screenplay) | Honey Irani (story)...,Govinda | Aishwarya Rai Bachchan | Jackie Shro...,Deepak Sareen,0.0,2
1,tt0169102,Lagaan: Once Upon a Time in India,2001,08 May 2002,Adventure | Drama | Musical,Ashutosh Gowariker (story) | Ashutosh Gowarike...,Aamir Khan | Gracy Singh | Rachel Shelley | Pa...,Ashutosh Gowariker,0.0,6
2,tt0187279,Meri Biwi Ka Jawab Nahin,2004,02 Jul 2004,Action | Comedy,NaN,Akshay Kumar | Sridevi | Gulshan Grover | Laxm...,Pankaj Parashar | S.M. Iqbal,0.0,1
3,tt0222024,Hum Tumhare Hain Sanam,2002,24 May 2002,Drama | Romance,K.S. Adiyaman | Arun Kumar (assistant dialogue...,Shah Rukh Khan | Madhuri Dixit | Salman Khan |...,K.S. Adiyaman,0.0,4
4,tt0227194,One 2 Ka 4,2001,30 Mar 2001,Action | Comedy | Drama,Sanjay Chhel | Raaj Kumar Dahima (screenplay) ...,Shah Rukh Khan | Juhi Chawla | Jackie Shroff |...,Shashilal K. Nair,0.0,1
...,...,...,...,...,...,...,...,...,...,...
1279,tt4121522,Shuruaat Ka Interval,2014,15 Aug 2014,NaN,Aarti S. Bagdi | Amrit Raj Gupta | Krishan Hoo...,Kaivalya Chheda | Rajsekhar Aningi | Avidant B...,Aarti S. Bagdi | Amrit Raj Gupta | Krishan Hoo...,0.0,1
1280,tt4187650,Trip to Bhangarh,2014,28 Aug 2014,Horror,NaN,Manish Choudhary | Suzanna Mukherjee | Poonam ...,Jitendra Pawar,0.0,1
1281,tt4190220,Zed Plus,2014,28 Nov 2014,NaN,Chandra Prakash Dwivedi (screen play and dialo...,Adil Hussain | Ekavali Khanna | Kulbhushan Kha...,Chandra Prakash Dwivedi,0.0,1
1282,tt4219300,Gollu aur Pappu,2014,21 Nov 2014,Comedy,NaN,Vir Das | Sandeepa Dhar | Rahul Handa | Dimple...,Kabir Sadanand,0.0,1
1283,tt4228746,Zid,2014,28 Nov 2014,Thriller,Vivek Agnihotri | Rohit Malhotra,Shradha Das | Mohan Kapoor | Mannara | Karanvi...,Rohit Malhotra | Anubhav Sinha,0.0,2

In [21]:
print(bolly.columns)

Index(['imdbId', 'title', 'releaseYear', 'releaseDate', 'genre', 'writers',
       'actors', 'directors', 'sequel', 'hitFlop'],
      dtype='object')

Now, let's select the 'MovieName' column to see that it is a Series:

In [22]:
movie_names_series = bolly['title']
display(movie_names_series.head())
print(type(movie_names_series))

0                               Albela
1    Lagaan: Once Upon a Time in India
2             Meri Biwi Ka Jawab Nahin
3               Hum Tumhare Hain Sanam
4                           One 2 Ka 4
Name: title, dtype: object

<class 'pandas.core.series.Series'>

In [23]:
movie_names_series.mode()

0                         ...Yahaan
1       13B: Fear Has a New Address
2                       16 December
3                              1920
4                1920: Evil Returns
                   ...
1279       Zindagi Na Milegi Dobara
1280              Zindagi Tere Naam
1281                       Zokkomon
1282         Zor Lagaa Ke... Haiya!
1283                       Zubeidaa
Name: title, Length: 1284, dtype: object

In [24]:
movie_names_series.describe()

count     1284
unique    1284
top        Zid
freq         1
Name: title, dtype: object